name: mealorder
description: A meal ordering system.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^0.16.0
  cupertino_icons: ^0.1.3
  firebase_auth: ^0.20.0+1
  firebase_core: ^0.7.0
  google_fonts: ^1.1.0
  google_maps_flutter: ^1.1.1
  intl: ^0.16.1
  lottie: ^0.7.0+1
  page_transition: ^1.1.7+6
  provider: ^4.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - animation/
